language: python
dist: xenial
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
  - sudo apt-get -y install python3-pyqt5
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
script: 
  - py.test --doctest-modules --cov
after_success: 
  - coveralls
