language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: 
  - py.test --doctest-modules --cov
after_success: 
  - coveralls
