language: python
python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
# just put in empty script of now
script: 
  - py.test --doctest-modules --cov
after_success: 
  - coveralls
