language: python
dist: xenial
python:
  - "3.6"
  - "3.8-dev"  # 3.6 development branch
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install pybids==0.9.5
  - pip install nilearn>=0.6.1
  - pip install templateflow>=0.4.1rc5
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - sudo apt-get -y install python3-pyqt5
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
script: 
  - py.test --doctest-modules --cov
after_success: 
  - coveralls
